# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:


- task: JFrogDocker@1
  inputs:
    command: 'Pull'
    artifactoryConnection: 'hts2-accesstoken'
    imageName: 'hts2-pruthvi-docker.jfrog.io/nginx:latest'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    skipLogin: false