# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'cloud'
    cliInstallationRepo: 'jf-remote'
    installCustomVersion: true
    cliVersion: '2.51.1'

- task: JFrogDocker@1
  inputs:
    command: 'Pull'
    artifactoryConnection: 'hts2-accesstoken'
    imageName: 'hts2-jana-docker-virtual.jfrog.io/nginx:latest'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    skipLogin: false

- task: JFrogDocker@1
  inputs:
    command: 'Push'
    artifactoryConnection: 'hts2-accesstoken'
    imageName: 'hts2-jana-docker-virtual.jfrog.io/nginx:latest'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    threads: '3'
    skipLogin: false'
   